# -*- coding: utf-8 -*-
"""Day-1_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sq2GZz2yMNGYzCpitNB0H_7LRlO5aeOz
"""

#assignment_day-1 (write a list in descending order)

li=[int(i) for i in input('enter values:').split()]

li.sort()
print(li)

#descending order

li.reverse()
print(li)